const messageType = [
  "Position Report Class A",
  "Position Report Class A (Assigned schedule)",
  "Position Report Class A (Response to interrogation)",
  "Base Station Report",
  "Static and Voyage Related Data",
  "Binary Addressed Message",
  "Binary Acknowledge",
  "Binary Broadcast Message",
  "Standard SAR Aircraft Position Report",
  "UTC and Date Inquiry",
  "UTC and Date Response",
  "Addressed Safety Related Message",
  "Safety Related Acknowledgement",
  "Safety Related Broadcast Message",
  "Interrogation",
  "Assignment Mode Command",
  "DGNSS Binary Broadcast Message",
  "Standard Class B CS Position Report",
  "Extended Class B Equipment Position Report",
  "Data Link Management",
  "Aid-to-Navigation Report",
  "Channel Management",
  "Group Assignment Command",
  "Static Data Report",
  "Single Slot Binary Message",
  "Multiple Slot Binary Message With Communications State",
  "Position Report For Long-Range Applications",
];

const navStatus = [
  "Under way using engine",
  "At anchor",
  "Not under command",
  "Restricted manoeuverability",
  "Constrained by her draught",
  "Moored",
  "Aground",
  "Engaged in Fishing",
  "Under way sailing",
  "Reserved for future amendment of Navigational Status for HSC",
  "Reserved for future amendment of Navigational Status for WIG",
  "Reserved for future use",
  "Reserved for future use",
  "Reserved for future use",
  "AIS-SART is active",
  "Not defined (default)",
];

const navAid = [
  "Default",
  "Type of Aid to Navigation not specified",
  "Reference point",
  "RACON (radar transponder marking a navigation hazard)",
  "Fixed structure off shore",
  "Spare, Reserved for future use.",
  "Light, without sectors",
  "Light, with sectors",
  "Leading Light Front",
  "Leading Light Rear",
  "Beacon, Cardinal N",
  "Beacon, Cardinal E",
  "Beacon, Cardinal S",
  "Beacon, Cardinal W",
  "Beacon, Port hand",
  "Beacon, Starboard hand",
  "Beacon, Preferred Channel port hand",
  "Beacon, Preferred Channel starboard hand",
  "Beacon, Isolated danger",
  "Beacon, Safe water",
  "Beacon, Special mark",
  "Cardinal Mark N",
  "Cardinal Mark E",
  "Cardinal Mark S",
  "Cardinal Mark W",
  "Port hand Mark",
  "Starboard hand Mark",
  "Preferred Channel Port hand",
  "Preferred Channel Starboard hand",
  "Isolated danger",
  "Safe Water",
  "Special Mark",
  "Light Vessel / LANBY / Rigs",
];

const epfd = [
  "GPS",
  "GLONASS",
  "Combined GPS/GLONASS",
  "Loran-C",
  "Chayka",
  "Integrated navigation system",
  "Surveyed",
  "Galileo",
];

const beaufort1 = [
  "Calm",
  "Light air",
  "Light breeze",
  "Gentle breeze",
  "Moderate breeze",
  "Fresh breeze",
  "Strong breeze",
  "High wind",
  "Gale",
  "Strong gale",
  "Storm",
  "Violent storm",
  "Hurricane force",
];

const beaufort2 = [
  "Flat",
  "Ripples without crests",
  "Small wavelets. Crests of glassy appearance, not breaking",
  "Large wavelets. Crests begin to break; scattered whitecaps",
  "Small waves",
  "Moderate (1.2 m) longer waves. Some foam and spray",
  "Large waves with foam crests and some spray",
  "Sea heaps up and foam begins to streak",
  "Moderately high waves with breaking crests forming spindrift. Streaks of foam",
  "High waves (6-7 m) with dense foam. Wave crests start to roll over. Considerable spray",
  "Very high waves. The sea surface is white and there is considerable tumbling. Visibility is reduced",
  "Exceptionally high waves",
  "Huge waves. Air filled with foam and spray. Sea completely white with driving spray. Visibility greatly reduced",
];

const precipitation = [
  "N/A",
  "Rain",
  "Thunderstorm",
  "Freezing rain",
  "Mixed/ice",
  "Snow",
  "N/A",
  "N/A (default)",
];

const weatherStation = [
  {
    id: 1,
    name: "Tulliniemi",
    lat1: 59.807,
    lat2: 59.8115,
    lon1: 22.9086,
    lon2: 22.9191,
    mentions: 0,
  },
  {
    id: 2,
    name: "Harmaja",
    lat1: 60.1037,
    lat2: 60.1065,
    lon1: 24.9703,
    lon2: 24.977,
    mentions: 0,
  },
  {
    id: 3,
    name: "Orrengrund",
    lat1: 60.2721,
    lat2: 60.2764,
    lon1: 26.435,
    lon2: 26.4471,
    mentions: 0,
  },
  {
    id: 4,
    name: "Rankki",
    lat1: 60.3649,
    lat2: 60.3802,
    lon1: 26.944,
    lon2: 26.975,
    mentions: 0,
  },
  {
    id: 5,
    name: "Haapasaari",
    lat1: 60.2852,
    lat2: 60.2916,
    lon1: 27.1814,
    lon2: 27.1978,
    mentions: 0,
  },
  {
    id: 6,
    name: "Tallinnamadala tuletorn",
    lat1: 59.7081,
    lat2: 59.7148,
    lon1: 24.7213,
    lon2: 24.7416,
    mentions: 0,
  },
  {
    id: 7,
    name: "Heltermaa",
    lat1: 58.8621,
    lat2: 58.8713,
    lon1: 23.0346,
    lon2: 23.0587,
    mentions: 0,
  },
];

const sixBitAscii = [
  "@",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "[",
  "\\",
  "]",
  "^",
  "_",
  " ",
  "!",
  '"',
  "#",
  "$",
  "%",
  "&",
  "'",
  "(",
  ")",
  "*",
  "+",
  ",",
  "-",
  ".",
  "/",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  ":",
  ";",
  "<",
  "=",
  ">",
  "?",
];

module.exports = {
  messageType,
  navStatus,
  navAid,
  epfd,
  beaufort1,
  beaufort2,
  precipitation,
  sixBitAscii,
};
